pipeline {
    agent any

    stages {
        stage('Plan') {
            steps {
                dir('non-prod') {
		    withAWS(profile: 'codeblock') {
		        sh 'yes | terragrunt plan-all'
                    }
		}
            }
        }
        stage('Apply') {
            steps {
                dir('non-prod') {
		    withAWS(profile: 'codeblock') {
                        sh 'terragrunt'
                    }
		}
            }
        }
    }
}

