pipeline {
    agent any

    stages {
        stage('Plan') {
            steps {
	    	dir('non-prod') {
		    sh 'yes | terragrunt plan-all'
		}
            }
        }
        stage('Apply') {
            steps {
                dir('non-prod') {
                    sh 'terragrunt'
		}
            }
        }
    }
}

